### PR TITLE
Update packages for security reasons.

### PR DESCRIPTION
**Pull request by zerebubuth**

### CODE REVIEW

**Comment by zerebubuth** [comment]
Hmm... not sure how to fix this. The version of Ruby on AWS (2.2.3) can't build the latest Chef, nor can it build `json =1.8.1`, which is required by `chef =11.10.4`. Possibly there are different Ruby versions bundled with AWS' opsworks? How can we set up the test environment to match that? Do we even care, if we're possibly moving away from Chef anyway?

**Comment by rmarianski** [comment]
My understanding is that the main problem is we would need to update to chef 12, and that's not something we want to do at this time.

**Comment by zerebubuth** [comment]
Yup. That's annoying. Thankfully, I think we don't load any YAML from the internet, so perhaps we can live with the vulnerable version until we move away from Chef?

**Comment by rmarianski** [comment]
> Yup. That's annoying. Thankfully, I think we don't load any YAML from the internet, so perhaps we can live with the vulnerable version until we move away from Chef?

Yea, I'm afraid that's the practical option. We only use ruby for chef here, so I think we should be ok too.

**Pull request closed without merging**
